footprint: [[-0.3, -0.15], [-0.3, 0.15], [0.3, 0.15], [0.3, -0.15]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions (for more information http://wiki.ros.org/navigation/Tutorials/RobotSetup)
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_sonar:
    topics: ["/sensor/sonar1", "/sensor/sonar2", "/sensor/sonar3", "/sensor/sonar4", "/sensor/sonar5"]
    no_readings_timeout: 1.0
    clear_threshold: 0.2
    mark_threshold: 0.8
    

inflation:
    inflation_radius: 1.0
