# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: littlebot_protocol.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'littlebot_protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18littlebot_protocol.proto\x12\tprotoblog\"\xc5\x01\n\x11LittlebotProtocol\x12\x44\n\x0fmotor_interface\x18\x03 \x03(\x0b\x32+.protoblog.LittlebotProtocol.MotorInterface\x1aj\n\x0eMotorInterface\x12\x0c\n\x04side\x18\x01 \x01(\x08\x12\x17\n\x0fstatus_velocity\x18\x02 \x01(\x02\x12\x17\n\x0fstatus_position\x18\x03 \x01(\x02\x12\x18\n\x10\x63ommand_velocity\x18\x04 \x01(\x02* \n\tMotorSide\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'littlebot_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTORSIDE']._serialized_start=239
  _globals['_MOTORSIDE']._serialized_end=271
  _globals['_LITTLEBOTPROTOCOL']._serialized_start=40
  _globals['_LITTLEBOTPROTOCOL']._serialized_end=237
  _globals['_LITTLEBOTPROTOCOL_MOTORINTERFACE']._serialized_start=131
  _globals['_LITTLEBOTPROTOCOL_MOTORINTERFACE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
