# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: littlebot_protocol.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'littlebot_protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18littlebot_protocol.proto\x12\tprotoblog\"\xae\x01\n\x11LittlebotProtocol\x12\x17\n\x0fleft_status_vel\x18\x01 \x01(\x02\x12\x17\n\x0fleft_status_pos\x18\x02 \x01(\x02\x12\x18\n\x10left_command_vel\x18\x03 \x01(\x02\x12\x18\n\x10right_status_vel\x18\x04 \x01(\x02\x12\x18\n\x10right_status_pos\x18\x05 \x01(\x02\x12\x19\n\x11right_command_vel\x18\x06 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'littlebot_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LITTLEBOTPROTOCOL']._serialized_start=40
  _globals['_LITTLEBOTPROTOCOL']._serialized_end=214
# @@protoc_insertion_point(module_scope)
