# Sphinx configuration file for the littlebot project.
# This file is picked up by Read the Docs based on .readthedocs.yaml

import os
import sys
import xml.etree.ElementTree as ET

# -- Path setup --------------------------------------------------------------
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here.
# sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------
project = 'littlebot'
author = 'NestorDP'

# Try to read package version from package.xml in the project root
_here = os.path.abspath(os.path.dirname(__file__))
_package_xml = os.path.abspath(os.path.join(_here, '..', 'package.xml'))
version = '0.0.0'
release = version
try:
    if os.path.exists(_package_xml):
        tree = ET.parse(_package_xml)
        root = tree.getroot()
        ver = root.find('version')
        if ver is not None and ver.text:
            release = ver.text.strip()
            # short X.Y version
            version = '.'.join(release.split('.')[:2])
except Exception:
    # fall back to default version above
    pass

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'breathe',
]

# Templates path
templates_path = ['_templates']

# The master toctree document.
master_doc = 'index'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------
try:
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
except Exception:
    html_theme = 'alabaster'

html_static_path = ['_static']

# -- Breathe (Doxygen XML) configuration ------------------------------------
# Read the Doxygen XML output generated by the Read the Docs pre-build step.
doxygen_xml_dir = os.path.join(_here, 'doxygen', 'xml')
if not os.path.isdir(doxygen_xml_dir):
    # also try upstream path in case docs are executed from another working dir
    doxygen_xml_dir = os.path.abspath(os.path.join(_here, '..', 'docs', 'doxygen', 'xml'))

breathe_projects = {
    project: doxygen_xml_dir
}
breathe_default_project = project

# Prefer the C++ domain for primary
primary_domain = 'cpp'
highlight_language = 'cpp'

# -- Autodoc / Napoleon settings --------------------------------------------
autodoc_default_options = {
    'members': True,
    'undoc-members': True,
    'show-inheritance': True,
}

napoleon_google_docstring = False
napoleon_numpy_docstring = True

# -- Intersphinx for cross-referencing common libraries ---------------------
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
}

# -- Todo extension ---------------------------------------------------------
todo_include_todos = True

# -- Additional helpers -----------------------------------------------------
def setup(app):
    # Expose project metadata for templates if necessary
    app.add_config_value('project_release', release, 'env')
    app.add_config_value('project_version', version, 'env')

# End of conf.py
