# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Quality
run-name: Run Lint Checks
on: [pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install cpplint flake8
      - name: Lint with flake8
        run: flake8
      - name: Lint with cpplint
        run: cpplint --recursive .
