# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ROS Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ros-tests:
    name: Run ROS Tests
    runs-on: ubuntu-24.04
    env:
      ROS_DISTRO: humble
    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ros_ws/src

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 2. Set up ROS 2
      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}

      # 3. Install dependencies with rosdep
      - name: Install dependencies
        run: |
          source /opt/ros/$ROS_DISTRO/setup.sh
          cd ros_ws
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -y

      # 4. Build the workspace
      - name: Build workspace
        run: |
          colcon build --symlink-install

      # 5. Source workspace and run tests (optional)
      - name: Run tests
        run: |
          source install/setup.bash
          colcon test
          colcon test-result --verbose
