name: ROS Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ros-tests:
    name: Run ROS Tests
    runs-on: ubuntu-24.04
    env:
      ROS_DISTRO: jazzy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ros_ws/src

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
          skip-rosdep: true

      - name: Install dependencies
        run: |
          source /opt/ros/$ROS_DISTRO/setup.sh
          cd ros_ws
          ./src/install_dependencies.sh

      # - name: Build workspace
      #   run: |
      #     colcon build --symlink-install

      # - name: Run tests
      #   run: |
      #     source install/setup.bash
      #     colcon test
      #     colcon test-result --verbose
